name: legends_panel
description: A panel to see your league of legends profile

# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.9.11+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  get:
  google_fonts: ^2.1.0
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  dio: ^4.0.0
  progress_indicators: ^1.0.0
  basic_utils: ^3.4.0
  flutter_feather_icons: ^2.0.0
  url_launcher: ^6.0.12
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  logger: ^1.0.0

flutter_icons:
  image_path: "images/launcher_icon_ios/icon_launcher_ios.png"
  android: true
  adaptive_icon_background: "images/launcher_icon_android/icon_background.png"
  adaptive_icon_foreground: "images/launcher_icon_android/icon_launcher_android.png"
  ios: true

flutter:

  uses-material-design: true
  generate: true
  assets:
     - images/
     - images/launcher_icon_android/
     - images/launcher_icon_ios/