name: legends_panel
description: A panel to see your league of legends profile

# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.20+20

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  get_it:
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  google_fonts: ^4.0.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_feather_icons: ^2.0.0
  url_launcher: ^6.0.12
  go_router: ^10.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  ios: false
  android: true
  image_path_android: "images/launcher_icon_android/icon_launcher_android.png"
  adaptive_icon_background: "images/launcher_icon_android/icon_background.png"
  adaptive_icon_foreground: "images/launcher_icon_android/icon_launcher_android.png"

flutter:

  uses-material-design: true
  generate: true
  assets:
     - images/
     - images/launcher_icon_android/
     - images/launcher_icon_ios/
     - images/home_background/